import java.awt.*;
import javax.swing.*;
import java.util.*;
import java.util.List;

public class interfaceCriativa {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Seja bem-vindo(a) às previsões do seu futuro!");
        frame.setSize(1920, 1080);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JPanel panel = new JPanel();
        panel.setBackground(new Color(127, 0, 255)); 
        panel.setLayout(new BorderLayout());

        JButton botao = new JButton("DESCUBRA A MENSAGEM ESCONDIDA... =====AGORA=====");
        botao.setBackground(Color.WHITE);
        botao.setPreferredSize(new Dimension(100, 100));
        botao.setFont(new Font("Serif", Font.BOLD, 36));

        JPanel formPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        formPanel.setOpaque(false); 
        JLabel label = new JLabel("Digite seu número da sorte ... (1 - 1000)");
        label.setFont(new Font("Serif", Font.BOLD, 36));
        label.setForeground(Color.WHITE);
        label.setBackground(new Color(255, 255, 255));
        JTextField textField = new JTextField(10);
        textField.setFont(new Font("Serif", Font.BOLD, 36));

        formPanel.add(label);
        formPanel.add(textField);

        ImageIcon imagem = new ImageIcon("imagens/futuro.png"); 
        JLabel imagemLabel = new JLabel(imagem);
        imagemLabel.setHorizontalAlignment(JLabel.CENTER);
        imagemLabel.setVerticalAlignment(JLabel.CENTER);

        // Lista de frases no lugar do switch
        List<String> frases = new ArrayList<>();
        frases.add("Um encontro inesperado mudará o rumo de algo que você nem sabia estar prestes a começar.");
        frases.add("Alguém do passado retornará — não para reatar, mas para revelar o que foi escondido.");
        frases.add("Antes que a última folha do outono caia, uma escolha sua abrirá um ciclo oculto.");
        frases.add("Você ouvirá uma frase comum... mas ela virá com um significado que mudará tudo.");
        frases.add("Um espelho mostrará mais do que sua imagem... mostrará um caminho esquecido.");
        frases.add("Quando o céu estiver mais cinza do que nunca, uma luz surgirá de onde você menos espera.");
        frases.add("Algo que você perdeu voltará... mas em outra forma, exigindo um novo olhar.");
        frases.add("Você encontrará um objeto antigo que carrega a resposta de uma pergunta ainda não feita.");
        frases.add("O vento tentará dizer algo enquanto você estiver de fones.");
        frases.add("Um poente apagará um ciclo esquecido.");
        frases.add("Uma borboleta vai te seguir por tempo demais para ser coincidência.");
        frases.add("O café será oferecido por mãos misteriosas... aceite.");
        frases.add("O Tempo guiará o que foi prometido em sonhos.");
frases.add("Um espelho transformará aquilo que você achava perdido.");
frases.add("Um espelho adormecerá um destino que insiste em ser cumprido.");
frases.add("Um eco desafiará aquilo que você achava perdido.");
frases.add("Um caminho sussurrará aquilo que você achava perdido.");
frases.add("Um tempo fechará aquilo que você achava perdido.");
frases.add("O Sussurro abrirá um destino que insiste em ser cumprido.");
frases.add("Um calafrio vai te atravessar, e não será o clima.");
frases.add("O Eco transformará um recomeço disfarçado de fim.");
frases.add("Um névoa sussurrará uma verdade antiga.");
frases.add("O Sombras ocultará um destino que insiste em ser cumprido.");
frases.add("Um olhar despertará uma verdade antiga.");
frases.add("Um estrela repetirá um recomeço disfarçado de fim.");
frases.add("O Sussurro repetirá aquilo que você achava perdido.");
frases.add("Um destino repetirá aquilo que você achava perdido.");
frases.add("Um olhar despertará um ciclo esquecido.");
frases.add("O Sussurro despertará o que foi prometido em sonhos.");
frases.add("Um relâmpago transformará um presságio envolto em mistério.");
frases.add("O Olhar fechará um presságio envolto em mistério.");
frases.add("O Tempo sussurrará uma mudança que o mundo pressentia.");
frases.add("O Espelho iluminará o que foi prometido em sonhos.");
frases.add("O Caminho adormecerá a resposta que você evita.");
frases.add("Um lua transformará aquilo que você achava perdido.");
frases.add("Um coração fechará um reflexo do que há por vir.");
frases.add("Um relâmpago trará um recomeço disfarçado de fim.");
frases.add("Um sussurro despertará um ciclo esquecido.");
frases.add("O Névoa fechará um recomeço disfarçado de fim.");
frases.add("Um silêncio sussurrará uma mudança que o mundo pressentia.");
frases.add("O Espelho despertará um presságio envolto em mistério.");
frases.add("Um lua iluminará um presságio envolto em mistério.");
frases.add("O Chave repetirá um reflexo do que há por vir.");
frases.add("Um portas provará a resposta que você evita.");
frases.add("O Olhar revelará um reflexo do que há por vir.");
frases.add("Um coração repetirá aquilo que você achava perdido.");
frases.add("O Caminho transformará aquilo que você achava perdido.");
frases.add("Um olhar repetirá uma verdade antiga.");
frases.add("Um poente despertará uma mudança que o mundo pressentia.");
frases.add("Um vento adormecerá a resposta que você evita.");
frases.add("O Sombras adormecerá um presságio envolto em mistério.");
frases.add("Um segredo provará um destino que insiste em ser cumprido.");
frases.add("O Poente fechará um presságio envolto em mistério.");
frases.add("O Poente apagará um ciclo esquecido.");
frases.add("O Portas revelará uma mudança que o mundo pressentia.");
frases.add("O Espelho repetirá uma mudança que o mundo pressentia.");
frases.add("O Portas desafiará um presságio envolto em mistério.");
frases.add("Um caminho provará um recomeço disfarçado de fim.");
frases.add("O Coração abrirá uma mudança que o mundo pressentia.");
frases.add("Um eco iluminará a resposta que você evita.");
frases.add("O Caminho desafiará aquilo que você achava perdido.");
frases.add("O Estrela sussurrará aquilo que você achava perdido.");
frases.add("Um coração repetirá a resposta que você evita.");
frases.add("O Manhã provará um presságio envolto em mistério.");
frases.add("Um poente repetirá o que foi prometido em sonhos.");
frases.add("Um manhã abrirá um recomeço disfarçado de fim.");
frases.add("O Chave trará um ciclo esquecido.");
frases.add("Um sombras apagará uma mudança que o mundo pressentia.");
frases.add("O Poente despertará um ciclo esquecido.");
frases.add("Um destino sussurrará um presságio envolto em mistério.");
frases.add("Um silêncio apagará um recomeço disfarçado de fim.");
frases.add("Um silêncio ocultará a resposta que você evita.");
frases.add("O Relâmpago trará um reflexo do que há por vir.");
frases.add("O Portas fechará o que foi prometido em sonhos.");
frases.add("O Tempo ocultará aquilo que você achava perdido.");
frases.add("O Caminho adormecerá uma verdade antiga.");
frases.add("Um portas trará um presságio envolto em mistério.");
frases.add("O Destino trará uma verdade antiga.");
frases.add("Um vento adormecerá o que foi prometido em sonhos.");
frases.add("O Lua revelará um ciclo esquecido.");
frases.add("Um névoa abrirá uma verdade antiga.");
frases.add("Um lua despertará um reflexo do que há por vir.");
frases.add("Um poente despertará o que foi prometido em sonhos.");
frases.add("O Segredo sussurrará um recomeço disfarçado de fim.");
frases.add("O Caminho iluminará um presságio envolto em mistério.");
frases.add("Um coração desafiará uma verdade antiga.");
frases.add("O Silêncio adormecerá a resposta que você evita.");
frases.add("Um eco transformará a resposta que você evita.");
frases.add("Um sombras desafiará um destino que insiste em ser cumprido.");
frases.add("O Relâmpago trará aquilo que você achava perdido.");
frases.add("O Névoa iluminará um reflexo do que há por vir.");
frases.add("Um manhã iluminará um recomeço disfarçado de fim.");
frases.add("O Manhã iluminará um recomeço disfarçado de fim.");
frases.add("O Coração revelará um presságio envolto em mistério.");
frases.add("Um eco desafiará o que foi prometido em sonhos.");
frases.add("Um estrela despertará uma verdade antiga.");
frases.add("Um silêncio guiará um ciclo esquecido.");
frases.add("O Chave guiará um recomeço disfarçado de fim.");
frases.add("Um caminho guiará um presságio envolto em mistério.");
frases.add("O Vento adormecerá a resposta que você evita.");
frases.add("O Segredo guiará um ciclo esquecido.");
frases.add("O Lua ocultará um recomeço disfarçado de fim.");
frases.add("O Olhar apagará aquilo que você achava perdido.");
frases.add("O Estrela provará o que foi prometido em sonhos.");
frases.add("O Coração trará um recomeço disfarçado de fim.");
frases.add("O Estrela despertará uma verdade antiga.");
frases.add("Um coração guiará uma verdade antiga.");
frases.add("O Sussurro iluminará uma verdade antiga.");
frases.add("Um portas apagará um recomeço disfarçado de fim.");
frases.add("Um espelho trará aquilo que você achava perdido.");
frases.add("O Poente guiará uma mudança que o mundo pressentia.");
frases.add("Um relâmpago sussurrará uma verdade antiga.");
frases.add("O Segredo revelará uma verdade antiga.");
frases.add("Um caminho abrirá a resposta que você evita.");
frases.add("Um destino transformará um ciclo esquecido.");
frases.add("O Sombras despertará um recomeço disfarçado de fim.");
frases.add("Um manhã revelará um presságio envolto em mistério.");
frases.add("O Vento sussurrará uma mudança que o mundo pressentia.");
frases.add("O Caminho provará um destino que insiste em ser cumprido.");
frases.add("Um silêncio trará um presságio envolto em mistério.");
frases.add("Um coração transformará o que foi prometido em sonhos.");
frases.add("Um olhar despertará a resposta que você evita.");
frases.add("Um estrela revelará uma verdade antiga.");
frases.add("Um caminho trará uma mudança que o mundo pressentia.");
frases.add("Um espelho revelará uma verdade antiga.");
frases.add("O Sussurro ocultará uma mudança que o mundo pressentia.");
frases.add("O Segredo sussurrará aquilo que você achava perdido.");
frases.add("Um vento despertará um recomeço disfarçado de fim.");
frases.add("O Chave desafiará o que foi prometido em sonhos.");
frases.add("Um tempo sussurrará um destino que insiste em ser cumprido.");
frases.add("O Olhar abrirá um ciclo esquecido.");
frases.add("Um sombras despertará um recomeço disfarçado de fim.");
frases.add("O Silêncio guiará um destino que insiste em ser cumprido.");
frases.add("O Névoa trará um destino que insiste em ser cumprido.");
frases.add("Um lua adormecerá um reflexo do que há por vir.");
frases.add("Um lua transformará uma mudança que o mundo pressentia.");
frases.add("O Olhar desafiará um reflexo do que há por vir.");
frases.add("O Sussurro iluminará um recomeço disfarçado de fim.");
frases.add("O Névoa ocultará uma mudança que o mundo pressentia.");
frases.add("O Sombras revelará o que foi prometido em sonhos.");
frases.add("O Espelho adormecerá aquilo que você achava perdido.");
frases.add("O Sussurro trará um presságio envolto em mistério.");
frases.add("Um caminho trará uma verdade antiga.");
frases.add("O Portas despertará aquilo que você achava perdido.");
frases.add("O Olhar ocultará um recomeço disfarçado de fim.");
frases.add("O Portas abrirá um presságio envolto em mistério.");
frases.add("O Manhã trará um recomeço disfarçado de fim.");
frases.add("Um chave adormecerá um reflexo do que há por vir.");
frases.add("O Manhã despertará um presságio envolto em mistério.");
frases.add("O Espelho apagará aquilo que você achava perdido.");
frases.add("Um vento fechará aquilo que você achava perdido.");
frases.add("Um chave fechará um presságio envolto em mistério.");
frases.add("Um névoa transformará uma verdade antiga.");
frases.add("O Lua sussurrará um reflexo do que há por vir.");
frases.add("O Coração despertará um destino que insiste em ser cumprido.");
frases.add("Um coração trará um reflexo do que há por vir.");
frases.add("Um manhã apagará a resposta que você evita.");
frases.add("Um estrela adormecerá aquilo que você achava perdido.");
frases.add("O Eco sussurrará um presságio envolto em mistério.");
frases.add("Um vento apagará o que foi prometido em sonhos.");
frases.add("Um eco iluminará um reflexo do que há por vir.");
frases.add("O Espelho desafiará um presságio envolto em mistério.");
frases.add("O Olhar guiará um presságio envolto em mistério.");
frases.add("Um sombras guiará um recomeço disfarçado de fim.");
frases.add("O Manhã sussurrará uma verdade antiga.");
frases.add("Um relâmpago guiará uma mudança que o mundo pressentia.");
frases.add("Um sombras repetirá um destino que insiste em ser cumprido.");
frases.add("Um sussurro sussurrará um destino que insiste em ser cumprido.");
frases.add("Um lua provará um presságio envolto em mistério.");
frases.add("O Espelho iluminará um recomeço disfarçado de fim.");
frases.add("Um espelho adormecerá a resposta que você evita.");
frases.add("Um segredo revelará aquilo que você achava perdido.");
frases.add("O Coração provará o que foi prometido em sonhos.");
frases.add("O Eco sussurrará aquilo que você achava perdido.");
frases.add("O Manhã trará aquilo que você achava perdido.");
frases.add("Um tempo apagará uma verdade antiga.");
frases.add("O Sombras guiará uma verdade antiga.");
frases.add("O Olhar adormecerá um reflexo do que há por vir.");
frases.add("Um segredo sussurrará a resposta que você evita.");
frases.add("O Espelho abrirá o que foi prometido em sonhos.");
frases.add("Um sombras provará o que foi prometido em sonhos.");
frases.add("O Caminho repetirá uma verdade antiga.");
frases.add("O Eco abrirá o que foi prometido em sonhos.");
frases.add("Um caminho fechará um presságio envolto em mistério.");
frases.add("O Lua provará uma verdade antiga.");
frases.add("O Coração abrirá o que foi prometido em sonhos.");
frases.add("Um vento adormecerá um reflexo do que há por vir.");
frases.add("Um sombras abrirá o que foi prometido em sonhos.");
frases.add("O Sussurro desafiará uma mudança que o mundo pressentia.");
frases.add("Um caminho fechará um presságio envolto em mistério.");
frases.add("Um silêncio abrirá um recomeço disfarçado de fim.");
frases.add("O Caminho abrirá uma verdade antiga.");
frases.add("O Manhã sussurrará uma mudança que o mundo pressentia.");
frases.add("O Lua revelará um recomeço disfarçado de fim.");
frases.add("Um chave iluminará uma mudança que o mundo pressentia.");
frases.add("Um sombras transformará o que foi prometido em sonhos.");
frases.add("Um sombras fechará um reflexo do que há por vir.");
frases.add("Um destino transformará um presságio envolto em mistério.");
frases.add("O Portas fechará um presságio envolto em mistério.");
frases.add("Um destino apagará um reflexo do que há por vir.");
frases.add("Um estrela trará um recomeço disfarçado de fim.");
frases.add("Um tempo revelará uma verdade antiga.");
frases.add("O Coração guiará um destino que insiste em ser cumprido.");
frases.add("O Vento adormecerá uma verdade antiga.");
frases.add("O Relâmpago fechará uma verdade antiga.");
frases.add("O Portas guiará aquilo que você achava perdido.");
frases.add("Um chave despertará uma verdade antiga.");
frases.add("O Névoa ocultará aquilo que você achava perdido.");
frases.add("Um sombras apagará uma mudança que o mundo pressentia.");
frases.add("O Olhar desafiará um ciclo esquecido.");
frases.add("Um lua repetirá um presságio envolto em mistério.");
frases.add("O Coração abrirá o que foi prometido em sonhos.");
frases.add("Um caminho transformará a resposta que você evita.");
frases.add("O Sombras trará a resposta que você evita.");
frases.add("O Poente desafiará um destino que insiste em ser cumprido.");
frases.add("O Tempo despertará uma verdade antiga.");
frases.add("Um eco adormecerá a resposta que você evita.");
frases.add("Um tempo abrirá um destino que insiste em ser cumprido.");
frases.add("O Eco provará um presságio envolto em mistério.");
frases.add("O Estrela despertará um ciclo esquecido.");
frases.add("Um lua apagará a resposta que você evita.");
frases.add("O Segredo transformará o que foi prometido em sonhos.");
frases.add("Um coração guiará um recomeço disfarçado de fim.");
frases.add("O Estrela adormecerá um reflexo do que há por vir.");
frases.add("O Manhã fechará uma verdade antiga.");
frases.add("O Estrela adormecerá um presságio envolto em mistério.");
frases.add("Um portas fechará uma mudança que o mundo pressentia.");
frases.add("O Olhar revelará um destino que insiste em ser cumprido.");
frases.add("Um segredo ocultará aquilo que você achava perdido.");
frases.add("Um estrela abrirá um recomeço disfarçado de fim.");
frases.add("Um espelho fechará o que foi prometido em sonhos.");
frases.add("Um portas repetirá um ciclo esquecido.");
frases.add("Um caminho trará um recomeço disfarçado de fim.");
frases.add("O Lua sussurrará aquilo que você achava perdido.");
frases.add("O Caminho revelará aquilo que você achava perdido.");
frases.add("Um névoa repetirá o que foi prometido em sonhos.");
frases.add("O Portas adormecerá aquilo que você achava perdido.");
frases.add("Um névoa repetirá uma verdade antiga.");
frases.add("O Tempo repetirá uma verdade antiga.");
frases.add("O Sussurro transformará uma verdade antiga.");
frases.add("Um segredo guiará um destino que insiste em ser cumprido.");
frases.add("O Sombras desafiará um reflexo do que há por vir.");
frases.add("O Tempo fechará um presságio envolto em mistério.");
frases.add("Um coração apagará uma mudança que o mundo pressentia.");
frases.add("O Chave guiará a resposta que você evita.");
frases.add("Um sombras repetirá o que foi prometido em sonhos.");
frases.add("Um estrela transformará um recomeço disfarçado de fim.");
frases.add("Um coração iluminará uma mudança que o mundo pressentia.");
frases.add("O Relâmpago sussurrará uma mudança que o mundo pressentia.");
frases.add("O Eco revelará o que foi prometido em sonhos.");
frases.add("Um sussurro despertará uma verdade antiga.");
frases.add("O Tempo provará um ciclo esquecido.");
frases.add("O Espelho abrirá uma verdade antiga.");
frases.add("O Manhã iluminará a resposta que você evita.");
frases.add("Um sussurro despertará um reflexo do que há por vir.");
frases.add("Um portas adormecerá um reflexo do que há por vir.");
frases.add("Um eco transformará aquilo que você achava perdido.");
frases.add("Um espelho trará uma mudança que o mundo pressentia.");
frases.add("Um portas revelará a resposta que você evita.");
frases.add("Um sombras adormecerá uma verdade antiga.");
frases.add("O Sombras desafiará um destino que insiste em ser cumprido.");
frases.add("O Segredo ocultará um presságio envolto em mistério.");
frases.add("Um olhar provará um ciclo esquecido.");
frases.add("O Portas revelará um presságio envolto em mistério.");
frases.add("Um estrela revelará uma verdade antiga.");
frases.add("O Eco ocultará um recomeço disfarçado de fim.");
frases.add("Um vento transformará um destino que insiste em ser cumprido.");
frases.add("Um estrela sussurrará um reflexo do que há por vir.");
frases.add("O Destino repetirá um presságio envolto em mistério.");
frases.add("Um tempo despertará aquilo que você achava perdido.");
frases.add("Um névoa iluminará um recomeço disfarçado de fim.");
frases.add("Um vento desafiará uma mudança que o mundo pressentia.");
frases.add("O Portas iluminará a resposta que você evita.");
frases.add("O Manhã revelará um ciclo esquecido.");
frases.add("Um coração provará uma verdade antiga.");
frases.add("O Vento fechará o que foi prometido em sonhos.");
frases.add("Um tempo ocultará a resposta que você evita.");
frases.add("Um relâmpago ocultará a resposta que você evita.");
frases.add("O Vento guiará um presságio envolto em mistério.");
frases.add("O Sussurro revelará uma verdade antiga.");
frases.add("O Névoa provará a resposta que você evita.");
frases.add("Um silêncio revelará a resposta que você evita.");
frases.add("O Estrela iluminará um reflexo do que há por vir.");
frases.add("Um lua trará um presságio envolto em mistério.");
frases.add("Um olhar trará a resposta que você evita.");
frases.add("Um caminho iluminará um presságio envolto em mistério.");
frases.add("Um tempo provará aquilo que você achava perdido.");
frases.add("O Olhar iluminará a resposta que você evita.");
frases.add("O Estrela trará aquilo que você achava perdido.");
frases.add("O Caminho repetirá um destino que insiste em ser cumprido.");
frases.add("O Caminho adormecerá um destino que insiste em ser cumprido.");
frases.add("O Coração adormecerá a resposta que você evita.");
frases.add("O Estrela despertará aquilo que você achava perdido.");
frases.add("O Sussurro despertará um ciclo esquecido.");
frases.add("O Lua sussurrará um presságio envolto em mistério.");
frases.add("Um estrela provará a resposta que você evita.");
frases.add("Um portas revelará um ciclo esquecido.");
frases.add("Um sussurro ocultará o que foi prometido em sonhos.");
frases.add("O Névoa apagará uma verdade antiga.");
frases.add("Um poente guiará o que foi prometido em sonhos.");
frases.add("O Poente abrirá um ciclo esquecido.");
frases.add("Um estrela repetirá a resposta que você evita.");
frases.add("O Coração guiará um recomeço disfarçado de fim.");
frases.add("O Olhar iluminará um ciclo esquecido.");
frases.add("Um sussurro provará a resposta que você evita.");
frases.add("O Segredo provará um reflexo do que há por vir.");
frases.add("O Chave repetirá o que foi prometido em sonhos.");
frases.add("Um chave ocultará um recomeço disfarçado de fim.");
frases.add("Um olhar abrirá uma verdade antiga.");
frases.add("Um chave apagará aquilo que você achava perdido.");
frases.add("Um silêncio guiará um reflexo do que há por vir.");
frases.add("Um manhã trará uma mudança que o mundo pressentia.");
frases.add("Um eco despertará um presságio envolto em mistério.");
frases.add("O Lua revelará uma mudança que o mundo pressentia.");
frases.add("Um lua abrirá um ciclo esquecido.");
frases.add("O Relâmpago iluminará um destino que insiste em ser cumprido.");
frases.add("Um tempo guiará o que foi prometido em sonhos.");
frases.add("O Tempo guiará um presságio envolto em mistério.");
frases.add("O Sussurro sussurrará uma verdade antiga.");
frases.add("Um névoa apagará aquilo que você achava perdido.");
frases.add("O Tempo repetirá um presságio envolto em mistério.");
frases.add("Um chave abrirá um destino que insiste em ser cumprido.");
frases.add("O Lua repetirá uma mudança que o mundo pressentia.");
frases.add("Um lua repetirá um reflexo do que há por vir.");
frases.add("O Sombras transformará um ciclo esquecido.");
frases.add("Um destino ocultará um reflexo do que há por vir.");
frases.add("Um manhã trará um recomeço disfarçado de fim.");
frases.add("Um eco adormecerá uma mudança que o mundo pressentia.");
frases.add("Um sussurro guiará o que foi prometido em sonhos.");
frases.add("Um tempo desafiará o que foi prometido em sonhos.");
frases.add("Um manhã despertará uma mudança que o mundo pressentia.");
frases.add("O Espelho apagará um reflexo do que há por vir.");
frases.add("O Sombras revelará uma mudança que o mundo pressentia.");
frases.add("O Olhar ocultará um ciclo esquecido.");
frases.add("O Relâmpago trará um ciclo esquecido.");
frases.add("Um olhar guiará a resposta que você evita.");
frases.add("O Estrela guiará uma verdade antiga.");
frases.add("O Chave revelará um destino que insiste em ser cumprido.");
frases.add("Um olhar desafiará um presságio envolto em mistério.");
frases.add("O Silêncio trará um destino que insiste em ser cumprido.");
frases.add("Um vento desafiará a resposta que você evita.");
frases.add("Um vento desafiará um destino que insiste em ser cumprido.");
frases.add("O Espelho despertará um presságio envolto em mistério.");
frases.add("Um chave adormecerá uma mudança que o mundo pressentia.");
frases.add("Um poente abrirá um destino que insiste em ser cumprido.");
frases.add("Um espelho transformará um reflexo do que há por vir.");
frases.add("O Névoa apagará um presságio envolto em mistério.");
frases.add("Um sussurro repetirá um reflexo do que há por vir.");
frases.add("Um caminho sussurrará uma mudança que o mundo pressentia.");
frases.add("O Névoa apagará uma verdade antiga.");
frases.add("O Sussurro sussurrará uma mudança que o mundo pressentia.");
frases.add("O Coração revelará um reflexo do que há por vir.");
frases.add("Um relâmpago fechará um destino que insiste em ser cumprido.");
frases.add("O Coração fechará um recomeço disfarçado de fim.");
frases.add("Um sombras guiará um recomeço disfarçado de fim.");
frases.add("Um lua repetirá o que foi prometido em sonhos.");
frases.add("Um lua desafiará um presságio envolto em mistério.");
frases.add("Um relâmpago guiará um recomeço disfarçado de fim.");
frases.add("Um coração guiará um reflexo do que há por vir.");
frases.add("Um destino abrirá uma mudança que o mundo pressentia.");
frases.add("O Tempo abrirá o que foi prometido em sonhos.");
frases.add("O Caminho guiará aquilo que você achava perdido.");
frases.add("O Coração ocultará o que foi prometido em sonhos.");
frases.add("Um estrela trará uma verdade antiga.");
frases.add("Um segredo revelará um presságio envolto em mistério.");
frases.add("O Sombras iluminará um ciclo esquecido.");
frases.add("O Destino abrirá um reflexo do que há por vir.");
frases.add("O Espelho abrirá um presságio envolto em mistério.");
frases.add("O Relâmpago fechará uma verdade antiga.");
frases.add("O Portas guiará um destino que insiste em ser cumprido.");
frases.add("Um coração repetirá um presságio envolto em mistério.");
frases.add("O Silêncio adormecerá um presságio envolto em mistério.");
frases.add("O Sombras revelará um destino que insiste em ser cumprido.");
frases.add("O Manhã apagará aquilo que você achava perdido.");
frases.add("Um sussurro apagará o que foi prometido em sonhos.");
frases.add("Um coração desafiará aquilo que você achava perdido.");
frases.add("Um lua despertará um reflexo do que há por vir.");
frases.add("Um segredo transformará uma verdade antiga.");
frases.add("O Tempo trará o que foi prometido em sonhos.");
frases.add("Um névoa sussurrará um reflexo do que há por vir.");
frases.add("O Tempo sussurrará uma verdade antiga.");
frases.add("O Olhar desafiará um recomeço disfarçado de fim.");
frases.add("Um silêncio sussurrará um ciclo esquecido.");
frases.add("Um eco provará o que foi prometido em sonhos.");
frases.add("O Destino abrirá um ciclo esquecido.");
frases.add("Um lua adormecerá aquilo que você achava perdido.");
frases.add("O Relâmpago apagará o que foi prometido em sonhos.");
frases.add("Um estrela apagará o que foi prometido em sonhos.");
frases.add("O Relâmpago guiará um ciclo esquecido.");
frases.add("O Segredo apagará a resposta que você evita.");
frases.add("Um eco guiará um presságio envolto em mistério.");
frases.add("O Espelho fechará aquilo que você achava perdido.");
frases.add("Um destino sussurrará um destino que insiste em ser cumprido.");
frases.add("O Sombras iluminará um presságio envolto em mistério.");
frases.add("Um espelho guiará a resposta que você evita.");
frases.add("Um manhã trará um reflexo do que há por vir.");
frases.add("O Silêncio revelará um destino que insiste em ser cumprido.");
frases.add("Um portas revelará a resposta que você evita.");
frases.add("O Relâmpago iluminará um recomeço disfarçado de fim.");
frases.add("Um espelho ocultará aquilo que você achava perdido.");
frases.add("Um eco trará o que foi prometido em sonhos.");
frases.add("O Vento adormecerá a resposta que você evita.");
frases.add("Um destino revelará uma verdade antiga.");
frases.add("Um poente transformará um destino que insiste em ser cumprido.");
frases.add("O Poente despertará uma mudança que o mundo pressentia.");
frases.add("O Eco desafiará a resposta que você evita.");
frases.add("Um olhar sussurrará uma mudança que o mundo pressentia.");
frases.add("Um segredo apagará um reflexo do que há por vir.");
frases.add("Um silêncio guiará uma verdade antiga.");
frases.add("Um manhã apagará a resposta que você evita.");
frases.add("O Portas transformará a resposta que você evita.");
frases.add("O Sussurro trará a resposta que você evita.");
frases.add("Um destino transformará a resposta que você evita.");
frases.add("Um coração trará um destino que insiste em ser cumprido.");
frases.add("O Tempo repetirá um destino que insiste em ser cumprido.");
frases.add("Um lua revelará aquilo que você achava perdido.");
frases.add("O Névoa repetirá um recomeço disfarçado de fim.");
frases.add("O Chave abrirá um presságio envolto em mistério.");
frases.add("Um poente revelará um ciclo esquecido.");
frases.add("Um manhã transformará um recomeço disfarçado de fim.");
frases.add("Um tempo apagará um presságio envolto em mistério.");
frases.add("Um coração trará um presságio envolto em mistério.");
frases.add("Um chave guiará um reflexo do que há por vir.");
frases.add("O Olhar guiará um presságio envolto em mistério.");
frases.add("Um sombras trará um destino que insiste em ser cumprido.");
frases.add("Um vento ocultará um recomeço disfarçado de fim.");
frases.add("Um tempo repetirá uma verdade antiga.");
frases.add("O Caminho revelará um ciclo esquecido.");
frases.add("O Névoa abrirá o que foi prometido em sonhos.");
frases.add("Um olhar trará uma verdade antiga.");
frases.add("O Névoa provará o que foi prometido em sonhos.");
frases.add("O Espelho sussurrará um ciclo esquecido.");
frases.add("Um silêncio revelará uma mudança que o mundo pressentia.");
frases.add("O Manhã sussurrará a resposta que você evita.");
frases.add("O Sombras adormecerá um reflexo do que há por vir.");
frases.add("O Névoa adormecerá uma mudança que o mundo pressentia.");
frases.add("O Manhã abrirá um reflexo do que há por vir.");
frases.add("O Segredo adormecerá um destino que insiste em ser cumprido.");
frases.add("O Tempo apagará a resposta que você evita.");
frases.add("Um relâmpago ocultará uma verdade antiga.");
frases.add("Um sussurro trará um presságio envolto em mistério.");
frases.add("Um espelho trará uma mudança que o mundo pressentia.");
frases.add("O Caminho guiará um recomeço disfarçado de fim.");
frases.add("Um sussurro abrirá a resposta que você evita.");
frases.add("Um destino provará um ciclo esquecido.");
frases.add("O Segredo desafiará a resposta que você evita.");
frases.add("Um relâmpago repetirá o que foi prometido em sonhos.");
frases.add("O Relâmpago desafiará um destino que insiste em ser cumprido.");
frases.add("Um poente iluminará um recomeço disfarçado de fim.");
frases.add("Um relâmpago iluminará um recomeço disfarçado de fim.");
frases.add("O Estrela trará um ciclo esquecido.");
frases.add("Um olhar fechará aquilo que você achava perdido.");
frases.add("O Eco apagará uma mudança que o mundo pressentia.");
frases.add("O Tempo desafiará um ciclo esquecido.");
frases.add("Um relâmpago abrirá uma mudança que o mundo pressentia.");
frases.add("Um névoa fechará um ciclo esquecido.");
frases.add("Um sombras despertará um destino que insiste em ser cumprido.");
frases.add("Um vento provará o que foi prometido em sonhos.");
frases.add("Um espelho desafiará uma verdade antiga.");
frases.add("O Destino guiará um recomeço disfarçado de fim.");
frases.add("O Sombras revelará um ciclo esquecido.");
frases.add("O Névoa trará um reflexo do que há por vir.");
frases.add("O Caminho provará um ciclo esquecido.");
frases.add("Um olhar apagará um ciclo esquecido.");
frases.add("Um silêncio apagará o que foi prometido em sonhos.");
frases.add("Um coração guiará uma verdade antiga.");
frases.add("Um sombras adormecerá aquilo que você achava perdido.");
frases.add("Um névoa revelará uma mudança que o mundo pressentia.");
frases.add("Um portas desafiará o que foi prometido em sonhos.");
frases.add("O Segredo repetirá um presságio envolto em mistério.");
frases.add("O Olhar apagará um presságio envolto em mistério.");
frases.add("O Névoa adormecerá a resposta que você evita.");
frases.add("O Destino trará um presságio envolto em mistério.");
frases.add("O Poente transformará a resposta que você evita.");
frases.add("O Sussurro apagará um recomeço disfarçado de fim.");
frases.add("O Névoa iluminará um recomeço disfarçado de fim.");
frases.add("O Eco abrirá um recomeço disfarçado de fim.");
frases.add("O Relâmpago trará uma mudança que o mundo pressentia.");
frases.add("Um manhã abrirá a resposta que você evita.");
frases.add("O Portas sussurrará um recomeço disfarçado de fim.");
frases.add("O Destino revelará o que foi prometido em sonhos.");
frases.add("O Relâmpago trará um presságio envolto em mistério.");
frases.add("Um lua iluminará aquilo que você achava perdido.");
frases.add("Um sombras despertará uma mudança que o mundo pressentia.");
frases.add("O Silêncio repetirá o que foi prometido em sonhos.");
frases.add("Um sombras revelará um presságio envolto em mistério.");
frases.add("O Segredo iluminará um recomeço disfarçado de fim.");
frases.add("O Sombras adormecerá a resposta que você evita.");
frases.add("O Silêncio guiará um destino que insiste em ser cumprido.");
frases.add("Um chave iluminará um recomeço disfarçado de fim.");
frases.add("O Destino provará a resposta que você evita.");
frases.add("Um poente repetirá um ciclo esquecido.");
frases.add("Um sussurro despertará o que foi prometido em sonhos.");
frases.add("Um eco repetirá um reflexo do que há por vir.");
frases.add("O Olhar adormecerá um ciclo esquecido.");
frases.add("Um sombras desafiará uma verdade antiga.");
frases.add("Um eco ocultará um destino que insiste em ser cumprido.");
frases.add("Um portas fechará a resposta que você evita.");
frases.add("O Portas apagará um destino que insiste em ser cumprido.");
frases.add("O Tempo despertará um recomeço disfarçado de fim.");
frases.add("Um névoa provará um ciclo esquecido.");
frases.add("Um relâmpago fechará um recomeço disfarçado de fim.");
frases.add("O Relâmpago adormecerá um destino que insiste em ser cumprido.");
frases.add("Um olhar guiará a resposta que você evita.");
frases.add("Um espelho repetirá uma mudança que o mundo pressentia.");
frases.add("O Tempo fechará uma mudança que o mundo pressentia.");
frases.add("Um destino repetirá um recomeço disfarçado de fim.");
frases.add("O Névoa adormecerá um recomeço disfarçado de fim.");
frases.add("O Lua repetirá a resposta que você evita.");
frases.add("O Estrela despertará aquilo que você achava perdido.");
frases.add("O Caminho desafiará um ciclo esquecido.");
frases.add("O Coração sussurrará um reflexo do que há por vir.");
frases.add("O Espelho revelará um recomeço disfarçado de fim.");
frases.add("Um silêncio abrirá uma verdade antiga.");
frases.add("O Poente iluminará um presságio envolto em mistério.");
frases.add("Um sussurro desafiará uma verdade antiga.");
frases.add("O Espelho apagará um reflexo do que há por vir.");
frases.add("Um névoa revelará uma verdade antiga.");
frases.add("O Silêncio repetirá aquilo que você achava perdido.");
frases.add("O Sombras trará uma verdade antiga.");
frases.add("O Relâmpago provará uma mudança que o mundo pressentia.");
frases.add("Um silêncio transformará aquilo que você achava perdido.");
frases.add("Um espelho fechará aquilo que você achava perdido.");
frases.add("O Poente fechará o que foi prometido em sonhos.");
frases.add("Um lua revelará um presságio envolto em mistério.");
frases.add("O Chave ocultará aquilo que você achava perdido.");
frases.add("Um segredo repetirá aquilo que você achava perdido.");
frases.add("Um lua guiará um presságio envolto em mistério.");
frases.add("Um sombras trará um recomeço disfarçado de fim.");
frases.add("O Sussurro provará uma verdade antiga.");
frases.add("Um lua revelará aquilo que você achava perdido.");
frases.add("Um destino transformará o que foi prometido em sonhos.");
frases.add("O Manhã guiará uma mudança que o mundo pressentia.");
frases.add("O Destino ocultará um presságio envolto em mistério.");
frases.add("Um chave sussurrará um reflexo do que há por vir.");
frases.add("O Segredo revelará um ciclo esquecido.");
frases.add("O Relâmpago fechará um ciclo esquecido.");
frases.add("Um portas iluminará aquilo que você achava perdido.");
frases.add("O Chave ocultará um destino que insiste em ser cumprido.");
frases.add("Um olhar guiará aquilo que você achava perdido.");
frases.add("O Segredo transformará um ciclo esquecido.");
frases.add("Um tempo revelará um destino que insiste em ser cumprido.");
frases.add("O Névoa adormecerá um reflexo do que há por vir.");
frases.add("O Tempo fechará um destino que insiste em ser cumprido.");
frases.add("O Espelho abrirá uma mudança que o mundo pressentia.");
frases.add("Um sussurro transformará uma verdade antiga.");
frases.add("O Tempo ocultará aquilo que você achava perdido.");
frases.add("O Manhã revelará aquilo que você achava perdido.");
frases.add("Um sombras despertará um presságio envolto em mistério.");
frases.add("Um coração abrirá um ciclo esquecido.");
frases.add("Um segredo ocultará aquilo que você achava perdido.");
frases.add("O Eco sussurrará um ciclo esquecido.");
frases.add("O Portas apagará um ciclo esquecido.");
frases.add("Um portas revelará um presságio envolto em mistério.");
frases.add("Um chave repetirá um destino que insiste em ser cumprido.");
frases.add("Um lua despertará o que foi prometido em sonhos.");
frases.add("O Vento abrirá um destino que insiste em ser cumprido.");
frases.add("Um sussurro sussurrará uma verdade antiga.");
frases.add("Um espelho guiará um ciclo esquecido.");
frases.add("O Relâmpago fechará um ciclo esquecido.");
frases.add("Um tempo provará uma mudança que o mundo pressentia.");
frases.add("O Silêncio apagará um destino que insiste em ser cumprido.");
frases.add("Um névoa trará uma verdade antiga.");
frases.add("Um vento despertará aquilo que você achava perdido.");
frases.add("O Sombras guiará uma verdade antiga.");
frases.add("Um destino fechará o que foi prometido em sonhos.");
frases.add("Um lua iluminará o que foi prometido em sonhos.");
frases.add("O Vento despertará aquilo que você achava perdido.");
frases.add("Um relâmpago abrirá o que foi prometido em sonhos.");
frases.add("O Sombras iluminará aquilo que você achava perdido.");
frases.add("O Destino transformará um recomeço disfarçado de fim.");
frases.add("O Caminho iluminará uma verdade antiga.");
frases.add("Um portas guiará aquilo que você achava perdido.");
frases.add("O Sombras revelará um reflexo do que há por vir.");
frases.add("O Manhã ocultará um ciclo esquecido.");
frases.add("O Olhar fechará um presságio envolto em mistério.");
frases.add("O Poente provará a resposta que você evita.");
frases.add("Um sombras desafiará um reflexo do que há por vir.");
frases.add("O Sombras sussurrará a resposta que você evita.");
frases.add("O Relâmpago transformará um destino que insiste em ser cumprido.");
frases.add("O Olhar provará a resposta que você evita.");
frases.add("O Sombras trará uma verdade antiga.");
frases.add("Um silêncio apagará uma verdade antiga.");
frases.add("O Coração adormecerá um recomeço disfarçado de fim.");
frases.add("Um estrela adormecerá a resposta que você evita.");
frases.add("Um destino iluminará um reflexo do que há por vir.");
frases.add("Um poente despertará um destino que insiste em ser cumprido.");
frases.add("Um eco sussurrará a resposta que você evita.");
frases.add("Um lua despertará um ciclo esquecido.");
frases.add("Um estrela despertará aquilo que você achava perdido.");
frases.add("O Relâmpago adormecerá uma mudança que o mundo pressentia.");
frases.add("Um destino guiará um recomeço disfarçado de fim.");
frases.add("Um espelho desafiará aquilo que você achava perdido.");
frases.add("Um névoa provará um presságio envolto em mistério.");
frases.add("Um lua provará o que foi prometido em sonhos.");
frases.add("O Chave revelará um ciclo esquecido.");
frases.add("O Silêncio sussurrará um ciclo esquecido.");
frases.add("Um coração guiará um reflexo do que há por vir.");
frases.add("O Tempo ocultará um recomeço disfarçado de fim.");
frases.add("Um sussurro abrirá uma verdade antiga.");
frases.add("O Sussurro desafiará uma mudança que o mundo pressentia.");
frases.add("Um poente apagará um presságio envolto em mistério.");
frases.add("O Sombras iluminará a resposta que você evita.");
frases.add("O Poente iluminará uma mudança que o mundo pressentia.");
frases.add("O Estrela iluminará a resposta que você evita.");
frases.add("O Relâmpago provará uma verdade antiga.");
frases.add("O Segredo trará uma mudança que o mundo pressentia.");
frases.add("Um lua abrirá um reflexo do que há por vir.");
frases.add("Um destino adormecerá a resposta que você evita.");
frases.add("Um caminho desafiará um ciclo esquecido.");
frases.add("O Olhar transformará um reflexo do que há por vir.");
frases.add("O Chave fechará um ciclo esquecido.");
frases.add("O Vento abrirá o que foi prometido em sonhos.");
frases.add("O Poente sussurrará aquilo que você achava perdido.");
frases.add("Um espelho iluminará um destino que insiste em ser cumprido.");
frases.add("O Relâmpago despertará uma verdade antiga.");
frases.add("Um destino adormecerá o que foi prometido em sonhos.");
frases.add("Um destino abrirá um reflexo do que há por vir.");
frases.add("O Eco despertará aquilo que você achava perdido.");
frases.add("Um olhar trará um recomeço disfarçado de fim.");
frases.add("O Eco abrirá um destino que insiste em ser cumprido.");
frases.add("O Manhã sussurrará um ciclo esquecido.");
frases.add("O Lua provará um presságio envolto em mistério.");
frases.add("O Sussurro repetirá um presságio envolto em mistério.");
frases.add("O Poente apagará a resposta que você evita.");
frases.add("Um estrela fechará uma mudança que o mundo pressentia.");
frases.add("Um espelho iluminará uma mudança que o mundo pressentia.");
frases.add("Um manhã abrirá a resposta que você evita.");
frases.add("O Eco apagará aquilo que você achava perdido.");
frases.add("Um chave repetirá um recomeço disfarçado de fim.");
frases.add("O Relâmpago fechará um recomeço disfarçado de fim.");
frases.add("Um segredo desafiará um presságio envolto em mistério.");
frases.add("O Sombras trará um recomeço disfarçado de fim.");
frases.add("O Névoa repetirá aquilo que você achava perdido.");
frases.add("Um poente iluminará uma verdade antiga.");
frases.add("O Poente guiará um destino que insiste em ser cumprido.");
frases.add("O Lua abrirá a resposta que você evita.");
frases.add("Um sussurro guiará o que foi prometido em sonhos.");
frases.add("O Segredo despertará um recomeço disfarçado de fim.");
frases.add("O Coração transformará um recomeço disfarçado de fim.");
frases.add("Um segredo repetirá aquilo que você achava perdido.");
frases.add("O Segredo desafiará a resposta que você evita.");
frases.add("O Olhar trará uma mudança que o mundo pressentia.");
frases.add("O Sussurro repetirá uma verdade antiga.");
frases.add("O Lua iluminará o que foi prometido em sonhos.");
frases.add("Um eco adormecerá uma mudança que o mundo pressentia.");
frases.add("O Névoa sussurrará o que foi prometido em sonhos.");
frases.add("O Eco transformará um recomeço disfarçado de fim.");
frases.add("Um espelho repetirá um ciclo esquecido.");
frases.add("Um névoa desafiará uma verdade antiga.");
frases.add("O Silêncio iluminará um destino que insiste em ser cumprido.");
frases.add("Um névoa provará um destino que insiste em ser cumprido.");
frases.add("Um espelho fechará um presságio envolto em mistério.");
frases.add("Um silêncio apagará uma verdade antiga.");
frases.add("O Segredo sussurrará um presságio envolto em mistério.");
frases.add("Um poente provará uma verdade antiga.");
frases.add("O Chave iluminará um presságio envolto em mistério.");
frases.add("O Segredo adormecerá um reflexo do que há por vir.");
frases.add("Um vento guiará uma verdade antiga.");
frases.add("Um segredo iluminará uma mudança que o mundo pressentia.");
frases.add("Um espelho adormecerá um destino que insiste em ser cumprido.");
frases.add("O Relâmpago adormecerá uma verdade antiga.");
frases.add("O Eco iluminará um recomeço disfarçado de fim.");
frases.add("Um caminho fechará um destino que insiste em ser cumprido.");
frases.add("O Poente guiará aquilo que você achava perdido.");
frases.add("O Manhã guiará uma mudança que o mundo pressentia.");
frases.add("O Silêncio fechará um ciclo esquecido.");
frases.add("Um coração fechará um reflexo do que há por vir.");
frases.add("Um eco sussurrará um presságio envolto em mistério.");
frases.add("Um sombras guiará aquilo que você achava perdido.");
frases.add("O Estrela abrirá um recomeço disfarçado de fim.");
frases.add("O Chave adormecerá um reflexo do que há por vir.");
frases.add("Um portas guiará um reflexo do que há por vir.");
frases.add("O Sussurro adormecerá o que foi prometido em sonhos.");
frases.add("O Vento repetirá a resposta que você evita.");
frases.add("Um eco ocultará o que foi prometido em sonhos.");
frases.add("Um vento fechará a resposta que você evita.");
frases.add("Um caminho ocultará um presságio envolto em mistério.");
frases.add("Um tempo provará um reflexo do que há por vir.");
frases.add("Um manhã provará a resposta que você evita.");
frases.add("Um destino apagará um recomeço disfarçado de fim.");
frases.add("Um estrela revelará um recomeço disfarçado de fim.");
frases.add("O Olhar transformará um reflexo do que há por vir.");
frases.add("Um olhar apagará uma mudança que o mundo pressentia.");
frases.add("O Lua provará um reflexo do que há por vir.");
frases.add("O Sussurro revelará um destino que insiste em ser cumprido.");
frases.add("Um sussurro provará um destino que insiste em ser cumprido.");
frases.add("O Manhã revelará uma verdade antiga.");
frases.add("O Névoa despertará um reflexo do que há por vir.");
frases.add("O Olhar provará um reflexo do que há por vir.");
frases.add("Um vento trará uma verdade antiga.");
frases.add("O Sussurro ocultará o que foi prometido em sonhos.");
frases.add("Um espelho abrirá um reflexo do que há por vir.");
frases.add("Um névoa guiará o que foi prometido em sonhos.");
frases.add("O Portas iluminará um presságio envolto em mistério.");
frases.add("Um espelho ocultará uma verdade antiga.");
frases.add("O Portas sussurrará aquilo que você achava perdido.");
frases.add("O Portas trará um destino que insiste em ser cumprido.");
frases.add("Um tempo revelará uma mudança que o mundo pressentia.");
frases.add("Um destino abrirá aquilo que você achava perdido.");
frases.add("Um segredo trará aquilo que você achava perdido.");
frases.add("Um destino abrirá um presságio envolto em mistério.");
frases.add("O Relâmpago sussurrará uma verdade antiga.");
frases.add("O Chave iluminará um ciclo esquecido.");
frases.add("Um segredo iluminará um destino que insiste em ser cumprido.");
frases.add("Um silêncio guiará uma verdade antiga.");
frases.add("O Manhã despertará um ciclo esquecido.");
frases.add("O Caminho sussurrará aquilo que você achava perdido.");
frases.add("Um poente adormecerá a resposta que você evita.");
frases.add("O Chave iluminará aquilo que você achava perdido.");
frases.add("Um manhã desafiará um recomeço disfarçado de fim.");
frases.add("O Lua repetirá o que foi prometido em sonhos.");
frases.add("O Caminho abrirá um reflexo do que há por vir.");
frases.add("O Coração abrirá um reflexo do que há por vir.");
frases.add("Um lua ocultará o que foi prometido em sonhos.");
frases.add("O Coração ocultará um ciclo esquecido.");
frases.add("Um estrela apagará a resposta que você evita.");
frases.add("O Destino transformará um ciclo esquecido.");
frases.add("O Estrela iluminará um reflexo do que há por vir.");
frases.add("O Segredo revelará um ciclo esquecido.");
frases.add("O Poente fechará o que foi prometido em sonhos.");
frases.add("Um silêncio adormecerá uma verdade antiga.");
frases.add("O Vento guiará a resposta que você evita.");
frases.add("O Lua guiará um destino que insiste em ser cumprido.");
frases.add("Um poente repetirá um reflexo do que há por vir.");
frases.add("O Portas trará a resposta que você evita.");
frases.add("Um destino iluminará a resposta que você evita.");
frases.add("Um silêncio adormecerá aquilo que você achava perdido.");
frases.add("Um chave desafiará o que foi prometido em sonhos.");
frases.add("O Vento adormecerá uma verdade antiga.");
frases.add("Um tempo adormecerá uma mudança que o mundo pressentia.");
frases.add("Um segredo despertará o que foi prometido em sonhos.");
frases.add("O Estrela fechará um recomeço disfarçado de fim.");
frases.add("O Eco fechará a resposta que você evita.");
frases.add("O Manhã trará um destino que insiste em ser cumprido.");
frases.add("Um poente despertará uma verdade antiga.");
frases.add("O Lua ocultará uma verdade antiga.");
frases.add("O Coração adormecerá o que foi prometido em sonhos.");
frases.add("Um silêncio repetirá um presságio envolto em mistério.");
frases.add("O Olhar adormecerá uma mudança que o mundo pressentia.");
frases.add("Um sombras desafiará o que foi prometido em sonhos.");
frases.add("O Eco desafiará aquilo que você achava perdido.");
frases.add("Um coração sussurrará um reflexo do que há por vir.");
frases.add("O Sussurro adormecerá aquilo que você achava perdido.");
frases.add("Um relâmpago trará um destino que insiste em ser cumprido.");
frases.add("O Tempo despertará um reflexo do que há por vir.");
frases.add("Um coração sussurrará um recomeço disfarçado de fim.");
frases.add("O Espelho ocultará uma verdade antiga.");
frases.add("Um espelho provará um presságio envolto em mistério.");
frases.add("Um relâmpago desafiará um ciclo esquecido.");
frases.add("Um segredo trará uma mudança que o mundo pressentia.");
frases.add("Um manhã trará aquilo que você achava perdido.");
frases.add("O Olhar sussurrará um recomeço disfarçado de fim.");
frases.add("Um espelho transformará uma verdade antiga.");
frases.add("O Segredo adormecerá uma verdade antiga.");
frases.add("O Estrela fechará um ciclo esquecido.");
frases.add("Um caminho transformará aquilo que você achava perdido.");
frases.add("O Tempo transformará um presságio envolto em mistério.");
frases.add("O Olhar provará um reflexo do que há por vir.");
frases.add("Um tempo repetirá um reflexo do que há por vir.");
frases.add("Um relâmpago trará um ciclo esquecido.");
frases.add("O Silêncio abrirá a resposta que você evita.");
frases.add("O Coração apagará um ciclo esquecido.");
frases.add("Um estrela abrirá um destino que insiste em ser cumprido.");
frases.add("O Vento ocultará um reflexo do que há por vir.");
frases.add("Um espelho abrirá um ciclo esquecido.");
frases.add("O Coração provará uma verdade antiga.");
frases.add("O Chave guiará um ciclo esquecido.");
frases.add("Um espelho ocultará aquilo que você achava perdido.");
frases.add("O Tempo ocultará uma mudança que o mundo pressentia.");
frases.add("Um olhar revelará o que foi prometido em sonhos.");
frases.add("Um sombras provará um reflexo do que há por vir.");
frases.add("O Estrela transformará uma verdade antiga.");
frases.add("O Eco fechará um reflexo do que há por vir.");
frases.add("O Silêncio ocultará aquilo que você achava perdido.");
frases.add("O Lua provará aquilo que você achava perdido.");
frases.add("O Segredo provará aquilo que você achava perdido.");
frases.add("O Manhã fechará um presságio envolto em mistério.");
frases.add("Um silêncio repetirá aquilo que você achava perdido.");
frases.add("Um estrela despertará um recomeço disfarçado de fim.");
frases.add("Um coração ocultará um reflexo do que há por vir.");
frases.add("Um chave transformará um destino que insiste em ser cumprido.");
frases.add("Um segredo fechará um recomeço disfarçado de fim.");
frases.add("O Relâmpago trará uma verdade antiga.");
frases.add("O Portas revelará uma verdade antiga.");
frases.add("Um caminho apagará aquilo que você achava perdido.");
frases.add("Um sussurro sussurrará um recomeço disfarçado de fim.");
frases.add("O Lua desafiará aquilo que você achava perdido.");
frases.add("O Lua trará um ciclo esquecido.");
frases.add("O Espelho apagará um presságio envolto em mistério.");
frases.add("O Espelho desafiará o que foi prometido em sonhos.");
frases.add("O Sussurro iluminará aquilo que você achava perdido.");
frases.add("O Vento repetirá a resposta que você evita.");
frases.add("Um chave repetirá um presságio envolto em mistério.");
frases.add("O Névoa fechará uma mudança que o mundo pressentia.");
frases.add("O Vento guiará o que foi prometido em sonhos.");
frases.add("O Névoa transformará um reflexo do que há por vir.");
frases.add("O Olhar desafiará um destino que insiste em ser cumprido.");
frases.add("O Névoa revelará um reflexo do que há por vir.");
frases.add("O Névoa iluminará uma verdade antiga.");
frases.add("Um relâmpago iluminará uma verdade antiga.");
frases.add("O Relâmpago trará um destino que insiste em ser cumprido.");
frases.add("Um espelho despertará a resposta que você evita.");
frases.add("O Vento abrirá aquilo que você achava perdido.");
frases.add("O Eco trará o que foi prometido em sonhos.");
frases.add("O Névoa revelará uma mudança que o mundo pressentia.");
frases.add("Um manhã guiará um reflexo do que há por vir.");
frases.add("Um chave despertará um presságio envolto em mistério.");
frases.add("O Portas provará uma mudança que o mundo pressentia.");
frases.add("Um estrela repetirá um presságio envolto em mistério.");
frases.add("Um olhar apagará um ciclo esquecido.");
frases.add("Um portas despertará o que foi prometido em sonhos.");
frases.add("O Caminho iluminará um destino que insiste em ser cumprido.");
frases.add("O Lua provará um presságio envolto em mistério.");
frases.add("Um silêncio iluminará uma mudança que o mundo pressentia.");
frases.add("O Silêncio guiará um recomeço disfarçado de fim.");
frases.add("O Estrela transformará um recomeço disfarçado de fim.");
frases.add("Um estrela ocultará o que foi prometido em sonhos.");
frases.add("O Olhar fechará um reflexo do que há por vir.");
frases.add("Um sombras desafiará um recomeço disfarçado de fim.");
frases.add("Um relâmpago abrirá um destino que insiste em ser cumprido.");
frases.add("Um sussurro ocultará o que foi prometido em sonhos.");
frases.add("Um caminho desafiará o que foi prometido em sonhos.");
frases.add("Um olhar guiará um ciclo esquecido.");
frases.add("Um silêncio apagará aquilo que você achava perdido.");
frases.add("O Olhar ocultará a resposta que você evita.");
frases.add("O Segredo adormecerá a resposta que você evita.");
frases.add("O Segredo guiará um presságio envolto em mistério.");
frases.add("O Caminho trará uma verdade antiga.");
frases.add("O Sussurro iluminará aquilo que você achava perdido.");
frases.add("Um portas revelará um ciclo esquecido.");
frases.add("Um relâmpago transformará aquilo que você achava perdido.");
frases.add("O Caminho despertará uma mudança que o mundo pressentia.");
frases.add("O Tempo repetirá o que foi prometido em sonhos.");
frases.add("Um caminho despertará uma verdade antiga.");
frases.add("O Espelho iluminará um ciclo esquecido.");
frases.add("Um vento revelará aquilo que você achava perdido.");
frases.add("Um sussurro revelará uma mudança que o mundo pressentia.");
frases.add("Um caminho sussurrará o que foi prometido em sonhos.");
frases.add("Um relâmpago fechará uma verdade antiga.");
frases.add("O Sombras sussurrará uma mudança que o mundo pressentia.");
frases.add("Um chave guiará um reflexo do que há por vir.");
frases.add("O Espelho sussurrará aquilo que você achava perdido.");
frases.add("O Portas provará um ciclo esquecido.");
frases.add("O Sussurro transformará um reflexo do que há por vir.");
frases.add("O Vento despertará um presságio envolto em mistério.");
frases.add("Um caminho iluminará aquilo que você achava perdido.");
frases.add("Um lua ocultará uma verdade antiga.");
frases.add("Um relâmpago abrirá um recomeço disfarçado de fim.");
frases.add("Um silêncio revelará um presságio envolto em mistério.");
frases.add("O Coração transformará uma mudança que o mundo pressentia.");
frases.add("Um caminho revelará a resposta que você evita.");
frases.add("Um vento guiará a resposta que você evita.");
frases.add("O Coração abrirá um presságio envolto em mistério.");
frases.add("Um destino provará uma verdade antiga.");
frases.add("Um estrela abrirá um recomeço disfarçado de fim.");
frases.add("Um destino guiará um presságio envolto em mistério.");
frases.add("Um relâmpago ocultará o que foi prometido em sonhos.");
frases.add("Um estrela fechará uma mudança que o mundo pressentia.");
frases.add("O Relâmpago ocultará um presságio envolto em mistério.");
frases.add("Um coração despertará um recomeço disfarçado de fim.");
frases.add("Um poente sussurrará o que foi prometido em sonhos.");
frases.add("O Tempo trará um ciclo esquecido.");
frases.add("Um segredo revelará uma mudança que o mundo pressentia.");
frases.add("Um manhã fechará a resposta que você evita.");
frases.add("O Poente revelará uma mudança que o mundo pressentia.");
frases.add("Um eco trará aquilo que você achava perdido.");
frases.add("Um silêncio abrirá um reflexo do que há por vir.");
frases.add("Um relâmpago guiará um ciclo esquecido.");
frases.add("Um sombras repetirá uma verdade antiga.");
frases.add("Um sombras sussurrará a resposta que você evita.");
frases.add("Um poente iluminará um ciclo esquecido.");
frases.add("O Silêncio desafiará uma mudança que o mundo pressentia.");
frases.add("Um manhã adormecerá um ciclo esquecido.");
frases.add("O Coração desafiará um presságio envolto em mistério.");
frases.add("Um segredo desafiará um recomeço disfarçado de fim.");
frases.add("Um caminho guiará a resposta que você evita.");
frases.add("O Estrela trará o que foi prometido em sonhos.");
frases.add("Um chave sussurrará uma verdade antiga.");
frases.add("O Destino despertará um destino que insiste em ser cumprido.");
frases.add("O Caminho iluminará uma verdade antiga.");
frases.add("Um eco apagará aquilo que você achava perdido.");
frases.add("O Silêncio trará um presságio envolto em mistério.");
frases.add("Um eco desafiará o que foi prometido em sonhos.");
frases.add("Um vento despertará aquilo que você achava perdido.");
frases.add("O Poente sussurrará a resposta que você evita.");
frases.add("O Silêncio fechará um reflexo do que há por vir.");
frases.add("O Olhar adormecerá um reflexo do que há por vir.");
frases.add("Um chave apagará uma verdade antiga.");
frases.add("Um relâmpago transformará um ciclo esquecido.");
frases.add("Um espelho abrirá um destino que insiste em ser cumprido.");
frases.add("O Vento adormecerá uma verdade antiga.");
frases.add("O Coração sussurrará a resposta que você evita.");
frases.add("O Portas sussurrará a resposta que você evita.");
frases.add("Um eco sussurrará um recomeço disfarçado de fim.");
frases.add("O Portas sussurrará um ciclo esquecido.");
frases.add("O Estrela sussurrará uma verdade antiga.");
frases.add("O Espelho guiará um presságio envolto em mistério.");
frases.add("O Silêncio guiará a resposta que você evita.");
frases.add("O Eco provará um recomeço disfarçado de fim.");
frases.add("Um coração despertará um presságio envolto em mistério.");
frases.add("O Espelho sussurrará o que foi prometido em sonhos.");
frases.add("O Relâmpago desafiará a resposta que você evita.");
frases.add("O Destino desafiará um destino que insiste em ser cumprido.");
frases.add("Um olhar ocultará um destino que insiste em ser cumprido.");
frases.add("Um chave guiará um presságio envolto em mistério.");
frases.add("O Manhã adormecerá o que foi prometido em sonhos.");
frases.add("O Sussurro adormecerá a resposta que você evita.");
frases.add("O Tempo ocultará uma verdade antiga.");
frases.add("O Espelho adormecerá o que foi prometido em sonhos.");
frases.add("Um estrela iluminará um recomeço disfarçado de fim.");
frases.add("O Relâmpago iluminará um presságio envolto em mistério.");
frases.add("Um estrela revelará um reflexo do que há por vir.");
frases.add("Um tempo provará uma verdade antiga.");
frases.add("Um caminho iluminará um recomeço disfarçado de fim.");
frases.add("Um névoa guiará um destino que insiste em ser cumprido.");
frases.add("O Poente abrirá o que foi prometido em sonhos.");
frases.add("Um sussurro guiará um ciclo esquecido.");
frases.add("O Sombras guiará aquilo que você achava perdido.");
frases.add("O Poente iluminará um presságio envolto em mistério.");
frases.add("Um relâmpago despertará uma verdade antiga.");
frases.add("O Lua abrirá um ciclo esquecido.");
frases.add("Um olhar desafiará aquilo que você achava perdido.");
frases.add("O Portas despertará um presságio envolto em mistério.");
frases.add("O Olhar despertará aquilo que você achava perdido.");
frases.add("O Silêncio adormecerá um reflexo do que há por vir.");
frases.add("Um poente provará uma mudança que o mundo pressentia.");
frases.add("O Segredo repetirá um destino que insiste em ser cumprido.");
frases.add("Um manhã guiará um reflexo do que há por vir.");
frases.add("O Portas revelará um reflexo do que há por vir.");
frases.add("Um tempo provará um ciclo esquecido.");
frases.add("O Lua revelará aquilo que você achava perdido.");
frases.add("O Chave desafiará um destino que insiste em ser cumprido.");
frases.add("Um olhar despertará aquilo que você achava perdido.");
frases.add("Um manhã ocultará um reflexo do que há por vir.");
frases.add("O Sussurro ocultará um reflexo do que há por vir.");
frases.add("Um segredo guiará aquilo que você achava perdido.");
frases.add("Um chave sussurrará uma mudança que o mundo pressentia.");
frases.add("O Manhã abrirá a resposta que você evita.");
frases.add("O Estrela provará uma mudança que o mundo pressentia.");
frases.add("Um lua sussurrará um destino que insiste em ser cumprido.");
frases.add("Um sombras revelará um presságio envolto em mistério.");
frases.add("O Lua trará uma verdade antiga.");
frases.add("O Portas abrirá o que foi prometido em sonhos.");
frases.add("O Névoa repetirá um recomeço disfarçado de fim.");
frases.add("O Lua fechará um reflexo do que há por vir.");
frases.add("Um lua ocultará um reflexo do que há por vir.");
frases.add("Um olhar guiará a resposta que você evita.");
frases.add("O Tempo desafiará a resposta que você evita.");
frases.add("O Segredo ocultará um reflexo do que há por vir.");
frases.add("Um destino fechará um ciclo esquecido.");
frases.add("O Tempo guiará uma verdade antiga.");
frases.add("Um silêncio trará aquilo que você achava perdido.");
frases.add("O Lua trará um destino que insiste em ser cumprido.");
frases.add("Um espelho abrirá um destino que insiste em ser cumprido.");
frases.add("Um chave transformará o que foi prometido em sonhos.");
frases.add("Um relâmpago adormecerá um ciclo esquecido.");
frases.add("Um estrela guiará o que foi prometido em sonhos.");
frases.add("Um segredo guiará uma verdade antiga.");
frases.add("Um espelho desafiará uma verdade antiga.");
frases.add("Um poente transformará um destino que insiste em ser cumprido.");
frases.add("Um olhar adormecerá um ciclo esquecido.");
frases.add("Um vento repetirá o que foi prometido em sonhos.");
frases.add("O Poente ocultará o que foi prometido em sonhos.");
frases.add("O Manhã provará um ciclo esquecido.");
frases.add("O Manhã fechará uma mudança que o mundo pressentia.");
frases.add("Um sussurro trará um reflexo do que há por vir.");
frases.add("O Silêncio despertará um recomeço disfarçado de fim.");
frases.add("O Caminho transformará aquilo que você achava perdido.");
frases.add("O Silêncio provará um destino que insiste em ser cumprido.");
frases.add("Um eco fechará a resposta que você evita.");
frases.add("Um eco provará um recomeço disfarçado de fim.");
frases.add("Um portas guiará um ciclo esquecido.");
frases.add("O Poente abrirá um ciclo esquecido.");
frases.add("Um portas abrirá o que foi prometido em sonhos.");
frases.add("O Destino guiará um presságio envolto em mistério.");
frases.add("O Tempo fechará uma verdade antiga.");
frases.add("Um poente fechará a resposta que você evita.");
frases.add("Um coração revelará uma mudança que o mundo pressentia.");
frases.add("O Névoa fechará um destino que insiste em ser cumprido.");
frases.add("O Segredo ocultará a resposta que você evita.");
frases.add("O Manhã revelará um recomeço disfarçado de fim.");
frases.add("O Manhã sussurrará um presságio envolto em mistério.");
frases.add("Um eco transformará o que foi prometido em sonhos.");
frases.add("Um segredo despertará uma mudança que o mundo pressentia.");
frases.add("O Destino trará um destino que insiste em ser cumprido.");
frases.add("Um tempo iluminará um presságio envolto em mistério.");
frases.add("Um coração provará uma verdade antiga.");
frases.add("Um coração iluminará um reflexo do que há por vir.");
frases.add("O Segredo transformará uma mudança que o mundo pressentia.");
frases.add("O Caminho apagará um ciclo esquecido.");
frases.add("Um estrela fechará um destino que insiste em ser cumprido.");
frases.add("O Segredo transformará um ciclo esquecido.");
frases.add("Um silêncio despertará um recomeço disfarçado de fim.");
frases.add("Um olhar abrirá aquilo que você achava perdido.");
frases.add("Um sombras iluminará um destino que insiste em ser cumprido.");
frases.add("O Caminho abrirá um destino que insiste em ser cumprido.");
frases.add("Um sussurro provará um ciclo esquecido.");
frases.add("O Névoa revelará um reflexo do que há por vir.");
frases.add("Um destino revelará um ciclo esquecido.");
frases.add("Um olhar trará o que foi prometido em sonhos.");
frases.add("Um espelho abrirá uma verdade antiga.");
frases.add("O Espelho revelará aquilo que você achava perdido.");
frases.add("Um vento provará o que foi prometido em sonhos.");
frases.add("Um olhar ocultará um recomeço disfarçado de fim.");
frases.add("Um eco provará o que foi prometido em sonhos.");
frases.add("O Silêncio sussurrará aquilo que você achava perdido.");
frases.add("O Sussurro transformará aquilo que você achava perdido.");
frases.add("O Chave adormecerá aquilo que você achava perdido.");
frases.add("Um sussurro guiará o que foi prometido em sonhos.");
frases.add("Um chave apagará um reflexo do que há por vir.");
frases.add("O Névoa repetirá a resposta que você evita.");

        botao.addActionListener(e -> {
            String entrada = textField.getText().trim();
            try {
                int mes = Integer.parseInt(entrada);
                String futuro;

                if (mes >= 1 && mes <= 1000) {
                    futuro = frases.get(mes - 1);
                } else {
                    futuro = "Mês inválido. Digite um número de 1 a 1000.";
                }

                JOptionPane.showMessageDialog(null, futuro, "Sua mensagem é...", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Digite um número válido (1 a 1000).", "Erro de entrada", JOptionPane.ERROR_MESSAGE);
            }
        });

        panel.add(formPanel, BorderLayout.NORTH);
        panel.add(imagemLabel, BorderLayout.CENTER); 
        panel.add(botao, BorderLayout.SOUTH);

        frame.add(panel);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
}
